[build]
target = "wasm32-unknown-unknown"
rustflags = ["-C", "target-feature=+bulk-memory,+atomics"]

[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"

[unstable]
build-std = ['std', 'panic_abort']
