[package]
name = "idb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idb-sys = { version = "0.1.0", path = "../idb-sys" }
js-sys = "0.3.58"
num-traits = "0.2.15"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["macros", "sync"] }
wasm-bindgen = "0.2.81"
web-sys = { version = "0.3.58", features = ["Event"] }

[dev-dependencies]
serde = { version = "1.0.138", features = ["derive"] }
serde-wasm-bindgen = "0.4.3"
serde_json = "1.0.82"
wasm-bindgen-test = "0.3.31"
web-sys = { version = "0.3.58", features = ["console"] }
